name: Post Tumblr Love Message

on:
  schedule:
    - cron: '0 13 * * *'  # Runs every day at 9AM EST (13:00 UTC)
  workflow_dispatch:      # Allows you to run it manually too

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TUMBLR_CONSUMER_KEY: ${{ secrets.TUMBLR_CONSUMER_KEY }}
      TUMBLR_CONSUMER_SECRET: ${{ secrets.TUMBLR_CONSUMER_SECRET }}
      TUMBLR_OAUTH_TOKEN: ${{ secrets.TUMBLR_OAUTH_TOKEN }}
      TUMBLR_OAUTH_SECRET: ${{ secrets.TUMBLR_OAUTH_SECRET }}
      TUMBLR_BLOG_NAME: ${{ secrets.TUMBLR_BLOG_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: python main.py
